# Site settings
title: Future home of Rich's stuff
email: richbodo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Robots vs. Kung Fu
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://richbodo.com" # the base hostname & protocol for your site
twitter_username: richbodo
github_username:  richbodo

# Build settings
markdown: kramdown
