# Site settings
title: Rich's stuff
email: richbodo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Writing and other projects by Rich Bodo
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://richbodo.com" # the base hostname & protocol for your site
twitter_username: richbodo
github_username:  richbodo

# Build settings
markdown: kramdown
exclude: [README.markdown, vendor]
